name: sync-peer-deps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-peer-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push on master branch

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run sync-peer-deps.js
      shell: bash
      run: |
        node scripts/sync-peer-deps.js

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: sync peerDependencies"
